Added todo list block for canvas
dcodermobile/Dcoder-community-blocks pull request #18
Opened 2022-02-08 21:03 UTC by nmghelani

Block that takes domain and token as input and returns todo list from canvas

2022-02-09 16:57 UTC, ankush-dcoder requested changes
Please use dist build method and complete requested changes. Also make sure to keep auto install off on your public block on Dcoder for these.

2022-02-09 16:57 UTC, ankush-dcoder commented on GetCanvasTODOList/dcoder_block.yml
> +  description: Authorization token
Provide details on how to get this token to help other users.

2022-02-09 16:57 UTC, ankush-dcoder commented on GetCanvasTODOList/dcoder_block.yml
> +  name: todoList
Provide description of output what does it return.

2022-02-09 16:57 UTC, ankush-dcoder commented on GetCanvasTODOList/dcoder_run.yml
> +  - run: |
Run this command using Dcoder_run or dcoder-cli to create a build in single file in dist folder.

2022-02-09 16:57 UTC, ankush-dcoder commented on GetCanvasTODOList/dcoder_block.yml
> +fileName: index.js
Follow instruction and build into single file and turn off auto install, and update here dist/index.js

2022-02-09 16:57 UTC, ankush-dcoder commented on GetCanvasTODOList/dcoder_block.yml
> +fileName: index.js
Read process in the Contributing.md, without build dist blocks are not accepted.
Auto install module blocks are generally slow compare to using a dist build.

2022-02-09 16:57 UTC, ankush-dcoder commented on GetCanvasInbox/dcoder_block.yml
> +fileName: index.js
Follow same comment for dist build and use dist/index.js here.

2022-02-09 23:10 UTC, nmghelani commented
Completed required changes @ankush-dcoder

2022-02-10 09:23 UTC, ankush-dcoder requested changes
Just 2 changes regarding error handling, everything else seems good.

2022-02-10 09:23 UTC, ankush-dcoder commented on GetCanvasInbox/index.js
> +  try{
Do not use try catch, let Dcoder's system handle the errors. If you catch the errors, system will not know that block got an error and will try to run flow ahead. No need of try catch here.

2022-02-10 09:23 UTC, ankush-dcoder commented on GetCanvasTODOList/index.js
> +  try{
Remove try catch, also remove on Dcoder block, then rebuild and release a new version for both blocks.

2022-02-10 10:14 UTC, nmghelani commented
Removed error handling and published the block to public @ankush-dcoder

2022-02-10 11:03 UTC, ankush-dcoder commented
@nmghelani can you get rid of all the semi colons. We do not use semicolons here for clean code.

2022-02-10 14:17 UTC, nmghelani commented
> @nmghelani can you get rid of all the semi colons. We do not use semicolons here for clean code.

Done ✅ @ankush-dcoder

2022-02-10 14:19 UTC, ankush-dcoder requested changes
Use single quotes for strings for consistency with repo logic.

2022-02-10 14:19 UTC, ankush-dcoder commented on GetCanvasInbox/index.js
> +const axios = require("axios")
Use single quotes for Strings everywhere.

2022-02-10 14:19 UTC, ankush-dcoder commented on GetCanvasInbox/index.js
> +  console.log("Fetching data")
Use single quote.

2022-02-10 14:19 UTC, ankush-dcoder commented on GetCanvasInbox/index.js
> +  console.log("Data fetched successfully")
Use single quote.

2022-02-10 15:44 UTC, merged